version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ant
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r AntExample-master1.zip dist/AntExample.war
      - aws s3 cp AntExample-master1.zip s3://akash.codedeploy.com/
